### ISSUE TITLE
Process PharmGKB scripts deprecated?

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/pharmacogx-embeddings#18]
Hello @GemmaTuron 

I wonder if the `src/process_pharmgkb` scripts are currently used anywhere in the repository. Just let me know.

Otherwise, we should do a bit of cleanup.

Thanks!

**Comment by GemmaTuron** [comment]
These are all the files used to process the PharmGKB data please do not delete them
They all work and I already cleaned up older/unused versions
