### ISSUE TITLE
Map variants to haplotypes in PharmGKB

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/pharmacogx-embeddings#8]
PharmGKB oftentimes puts together variants and haplotypes in the downloaded files (See for example, clinicalAnnotations)
We need to map each haplotype to the variants it contains (for example, for [CYP2B6*1](https://www.pharmgkb.org/haplotype/PA165818750)).
We will automaticlaly download all the available allele tables per gene, curate and add them to the existing files

**Comment by GemmaTuron** [comment]
This [commit](https://github.com/ersilia-os/pharmacogx-embeddings/commit/d2022ca162ecec0ad9a18df09b49be88ac700442) has created tables for each gene that contain the haplotype information and the different variants in each haplotype.

**Comment by miquelduranfrigola** [comment]
Hello @GemmaTuron - this is great stuff, thanks. As discussed, great that you deconvolute haplotypes to variants (see related issue #15)

**Comment by GemmaTuron** [comment]
This is already done in the mentioned commit.

**Comment by GemmaTuron** [comment]
I have improved the haplotype to variant deconvolution to ensure maximum correspondence in the variant name so that we can have all the variant ID (vid) which enable us to query pharmgkb easily using the API.
This is still work in progress as some variant names like the `NAT1 9bp deletion` do not correspond to the actual name in the API -- needs manual curation
[Commit](https://github.com/ersilia-os/pharmacogx-embeddings/commit/4cfb81ce38f668b8715f6bc43f879310ff0f1554)

**Comment by GemmaTuron** [comment]
I have finished the deconvolution, all variants inside haplotyps for which a variant ID is available are now associated in the file `hap_var_complete.csv`
changes in this [commit](a2354e7a55b8ca2f290fdbb5c0d6b34655033c5f).
